### ISSUE TITLE
Cannot enable cyber77 in vscode 1.70.+

### ISSUE THREAD

**Issue by lumenghz** [CodeReviewer14/Cyber-77-Synthwave-VSCode#2]
workbench dir in vscode 1.70 has changed

You can check https://github.com/robb0wen/synthwave-vscode/blob/master/src/extension.js#L29 for detail

**Comment by CodeReviewer14** [comment]
Thanks a lot for pointing this out, updated it, please let me know if the glow works now!

**Comment by lumenghz** [comment]
![image](https://user-images.githubusercontent.com/3817355/201250862-bc567b0d-980b-4147-8727-5234f717778c.png)

You may be missing a method named `isVSCodeBelowVersion`?

**Comment by CodeReviewer14** [comment]
Please try now

**Comment by lumenghz** [comment]
It works, thanks 😄
